### ISSUE TITLE
Training on my own data and training flag 

### ISSUE THREAD

**Issue by YJonmo** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#29]
Hi there,

Thanks for the great work. Help please! 

I am trying to train it on my won simulated endoscopic stereo data. 
I call the Train.py using this args:
python3 Train.py \
    --trainingSet ${TrainingSet} \
	--validationSet ${TrainingSet} \
    -o ${OUTPUT} \
    --modelName ${MODELNAME} \
	--imageShape 256 256

But I get the following error:
.
.
.
Starting Creation of Dispnet
==================================================
WARNING: flag for trainign not setted, using default False
WARNING: Correlation unspecified, setting to True
Args Validated, setting up graph
Meta op to preprocess data created
Network ready
==================================================
Traceback (most recent call last):
  File "Train.py", line 188, in <module>
    main(args)
  File "Train.py", line 99, in main
    assert(len(args.lossWeights)==len(predictions))
TypeError: object of type 'NoneType' has no len()

Thanks
Jacob

**Comment by YJonmo** [comment]
more precisely it is the len(args.lossWeights) which gives me the error as the print(len(predictions)) reveals 7. 
>> print(len(predictions)) 
       7

**Comment by YJonmo** [comment]
it looks like for the training there should be values for the --lossWeights and the default None value it not possible.

**Comment by AlessioTonioni** [comment]
> it looks like for the training there should be values for the --lossWeights and the default None value is not possible.

Thanks for pointing out the mistake, I'll update the code to handle properly the default value.

As for the second error is due to a `--imageShape` being wrongly used as the crop dimension for the images. I'll update the code accordingly.

**Comment by AlessioTonioni** [comment]
Should be fixed here:
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/commit/20add4c4ef087dd551b9de776a6d58a474a44d77

**Comment by YJonmo** [comment]
Thanks.

By the way do you know what could be Ok for the --lossWeights argument? I chose 0.001 0.001 0.005 0.01 0.02 0.08 0.32 weights. The result of training on the simulated stereo images was not smooth and rather look like a staircase. Any suggestion? 

Thanks

MODELNAME="Dispnet"
BLOCKCONFIG="block_config/Dispnet_full.json"
![Screenshot from 2019-11-11 11-10-55](https://user-images.githubusercontent.com/12040950/68554318-4eeb1200-0473-11ea-8736-28797cedf84b.png)

python3 Train.py \
    --trainingSet ${TrainingSet} \
	-o ${OUTPUT} \
    --modelName ${MODELNAME} \
	--imageShape 245 245 \
	--lossWeights 0.001 0.001 0.005 0.01 0.02 0.08 0.32

**Comment by AlessioTonioni** [comment]
Are you correctly reading disparity as float values? 
If you cast them to int and then transform to depth you might get this staircase effect due to the quantization.

Regarding the loss weights for the Dispnet training you can refer to the original Dispnet paper. Moreover if you use the default loss `mean_l1`, these values are too small.  The values in the paper were calibrated for `sum_l1`.

**Comment by YJonmo** [comment]
The output of the Stereo_Online_Adaptation.py is .png images, which I guess they are integer by definition (16 bit). 
That's how I read them:

img = cv2.imread('Depth0001_L.png', -1)
plt.hist(img[:,:].ravel(),100)
plt.show()
Which is what you see below:

![Screenshot from 2019-11-12 09-54-45](https://user-images.githubusercontent.com/12040950/68630061-d6975600-0531-11ea-97b7-7cb3c21df3e8.png)

**Comment by AlessioTonioni** [comment]
You are right, there was a quantization error when saving disparities with `Stereo_Online_Adaptation.py`, should be fixed in this commit https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/commit/da70c35a3189b75fa127df474ea41df3457d3388.

Try again, please.

> And just to clarify: should the ground truth depth images be of 16-bit png format?

The supported formats are 8/16-bit `png` and `pfm`. 
If you use 8-bit `png` or `pfm` the pixel intensities are directly used as gt values, therefore with 8 bit you only have integer gt labels (i.e, no subpixel disparity estimation).
If you use 16-bit `png`, first the raw pixel values in `uint16` are cast to `float` then they are subdivided by 256 and used as gt.
